version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      SA_PASSWORD: '0000' 
      ACCEPT_EULA: Y
    ports:
      - '3306:3306'

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'

  redis:
      container_name: redis
      image: redis:latest
      ports:
          - '6379:6379'