version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '0000' 
      ACCEPT_EULA: Y
    volumes:
      - //home/riley/DBdata/mydb:/var/lib/mysql
    ports:
      - '3306:3306'

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - //home/riley/DBdata/mdb:/data/db
    ports:
      - '27017:27017'

  redis:
      container_name: redis
      image: redis:latest
      volumes:
        - //home/riley/DBdata/rdb:/data
      ports:
          - '6379:6379'
volumes:
  mysqlvolume:
  mongovolume:
  redisvolume:
