version: "3.3"
services:

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: ./
    volumes:
      - ./Desktop/TEST
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    entrypoint: go run test.go
    restart: always
  mysql:
      image: mysql
      environment:
          SA_PASSWORD: '0000' 
          ACCEPT_EULA: Y
      ports:
          - '3306:3306'
  mongo:
      image: mongo
      environment:
          ACCEPT_EULA: Y
      ports:
          - '27017:27017'
  redis:
      image: redis
      environment:
          ACCEPT_EULA: Y
      ports:
          - '6379:6379'